---
title: "Figure Code"
author: "Christian Pascual"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(tidyverse)
library(glue)
```

```{r}
path = "simulations/standard"
d = tibble()
files = paste0("simulations/standard/",list.files(path))
sims = vector(mode = "list", length = length(files))

for (i in 1:length(files)) {
  t = readRDS(files[i])
  sims[[i]] = t
  print(i)
}

d = bind_rows(sims)


saveRDS(d, "standard-sims.rds")
```

# EPP Plot

```{r}
d = readRDS("standard-sims.rds")

epp = d %>% 
  select(EFFECT_SIZE, AR1_PHI, contains("prob")) %>% 
  pivot_longer(contains("prob"), names_to = "col", values_to = "probability") %>% 
  transmute(
    ES = factor(EFFECT_SIZE, levels = c(0, -2, -5, -10), 
                labels = c("Null", "Weak", "Moderate", "Large")),
    PHI = factor(AR1_PHI, levels = c(0, 25, 50, 75),
                 labels = c("0%", "25%", "50%", "75%")),
    probability = probability,
    treatment = str_extract(col, "X\\d+"),
    period = str_extract(col, "period\\d?\\d") %>% 
      str_replace("period", "") %>% as.numeric
  ) %>% 
  group_by(treatment, period, ES, PHI) %>% 
  summarize(n = n(), EPP = mean(probability))
```


```{r}
epp = d %>% 
    select(EFFECT_SIZE, AR1_PHI, contains("prob")) %>% 
    pivot_longer(contains("prob"), names_to = "col", values_to = "probability") %>% 
    transmute(
      ES = factor(EFFECT_SIZE, levels = c(0, -2, -5, -10), 
                  labels = c("Null", "Weak", "Moderate", "Large")),
      PHI = factor(AR1_PHI, levels = c(0, 25, 50, 75),
                   labels = c("0%", "25%", "50%", "75%")),
      probability = probability,
      treatment = str_extract(col, "X\\d+"),
      period = str_extract(col, "period\\d?\\d") %>% 
        str_replace("period", "") %>% as.numeric
    ) %>% 
    group_by(treatment, period, ES, PHI) %>% 
    summarize(n = n(), EPP = mean(probability))

Figure2()
Figure2b()
```

```{r}
epp %>% 
  filter(treatment == "X2", ES != "Null") %>% 
  ggplot(aes(x = period, y = EPP, color = PHI, group = PHI)) + 
  geom_hline(aes(yintercept = 1/3), alpha = 0.5, linetype = "dotted") +
  geom_line() +
  theme_minimal() + 
  theme(legend.position = "bottom") +
  facet_wrap(~ES) +
  labs(
    title = "Expected proportion of periods on optimal treatment by effect size"
  )
```


```{r}
source_folder <- "simulations/standard-bad"
destination_folder <- "simulations/standard"

# List of files to move
files = list.files(destination_folder)
files_to_move <- files[str_detect(files, "null_AR75")]

# Create full paths for source and destination
source_paths <- file.path(source_folder, files_to_move)
destination_paths <- file.path(destination_folder, files_to_move)

# Copy files to the destination folder
file.copy(from = source_paths, to = destination_paths, overwrite = TRUE)
f
# Optionally, remove the original files (uncomment the line below if you want to delete the original files)
# file.remove(source_paths)

```

